#!/bin/sh
# postrm script for ubuntu-kylin-theme
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
SUITE=$(lsb_release -sc)
for user in `users`
do
su - $user -c 'gsettings set org.gnome.desktop.interface gtk-theme Ambiance' 
su - $user -c 'gconftool-2 --set --type string /apps/metacity/general/theme  Ambiance'
su - $user -c 'gsettings set org.gnome.desktop.interface icon-theme ubuntu-mono-dark'
su - $user -c 'gconftool-2 --set --type string /desktop/gnome/peripherals/mouse/cursor_theme  DMZ-White'

su - $user -c 'gsettings set org.gnome.desktop.background  picture-uri  'file:///usr/share/backgrounds/Murales_by_Jan_Bencini.jpg''
done
ln -sf /usr/share/icons/DMZ-White/cursor.theme /etc/alternatives/x-cursor-theme
sed -i '/UbuntuKylin/d' /usr/share/gnome-background-properties/$SUITE-wallpapers.xml
#rm -rf /usr/share/icons/kylin-icon-theme
#rm -rf /usr/share/themes/kylin-theme
#rm -rf /usr/share/backgrounds/ubuntukylin.png


exit 0
