#!/bin/sh
#cp -raf /tmp/icons/kylin-icon-theme /usr/share/icons/
#rm -rf /tmp/icons

#cp -raf /tmp/themes/kylin-theme /usr/share/themes/
#rm -rf /tmp/themes

#cp -raf /tmp/backgrounds/ubuntukylin.png /usr/share/backgrounds/
#rm -rf /tmp/backgrounds
#sleep 5
SUITE=$(lsb_release -sc)
for user in `users`
do
su - $user -c 'gsettings set org.gnome.desktop.interface gtk-theme kylin-theme' 
su - $user -c 'gsettings set org.gnome.desktop.interface icon-theme kylin-icon-theme'
#for 12.04
#su - $user -c 'gconftool-2 --set --type string /apps/metacity/general/theme  kylin-theme'
#su - $user -c 'gconftool-2 --set --type string /desktop/gnome/peripherals/mouse/cursor_theme  kylin-icon-theme'
#for 13.04
su - $user -c 'gsettings set org.gnome.desktop.wm.preferences theme kylin-theme'
su - $user -c 'gsettings set org.gnome.desktop.interface cursor-theme kylin-icon-theme'


su - $user -c 'gsettings set org.gnome.desktop.background  picture-uri  'file:///usr/share/backgrounds/ubuntukylin.png''
done
ln -sf /usr/share/icons/kylin-icon-theme/cursor.theme /etc/alternatives/x-cursor-theme
#the file name is bug in test-version of 13.04
#sed -i '8a\<wallpaper><name>UbuntuKylin</name><filename>/usr/share/backgrounds/ubuntukylin.png</filename><options>zoom</options><pcolor>#000000</pcolor><scolor>#000000</scolor><shade_type>solid</shade_type></wallpaper>' /usr/share/gnome-background-properties/$SUITE-wallpapers.xml
exit 0
