debian/25_ubuntukylin-theme.gschema.override /usr/share/glib-2.0/schemas
debian/chinese /usr/share/initramfs-tools/hooks/
ukui-custom.xml /usr/share/mime/packages
usr/share/plymouth/themes/ubuntukylin-logo/
usr/share/plymouth/themes/ubuntukylin-text/
icons/ukui-classical icons/ukui icons/ukui-icon-theme-default usr/share/icons/
dark-sense/*.theme /usr/share/icons/dark-sense
dark-sense/cursors /usr/share/icons/dark-sense/
blue-crystal/*.theme /usr/share/icons/blue-crystal
blue-crystal/cursors /usr/share/icons/blue-crystal/



themes/ukui-dark themes/ukui-light themes/ukui-white themes/ukui-black themes/ukui usr/share/themes/
themes/ukui-light/gtk-3.0/ usr/share/themes/ukui/
themes/ukui-light/gtk-3.0/ usr/share/themes/ukui-white/
themes/ukui-dark/gtk-3.0/ usr/share/themes/ukui-black/

themes/ukui-light/gtk-2.0/ usr/share/themes/ukui/
themes/ukui-light/gtk-2.0/ usr/share/themes/ukui-white/
themes/ukui-dark/gtk-2.0/ usr/share/themes/ukui-black/

usr/share/fcitx-qimpanel/skin/ubuntukylin-dark1/
usr/share/fcitx-qimpanel/skin/ubuntukylin-dark2/
usr/share/fcitx-qimpanel/skin/ubuntukylin-light1/
usr/share/fcitx-qimpanel/skin/ubuntukylin-light2/
ubuntukylin-grub-theme/06_ubuntukylin_theme /etc/grub.d/
usr/share/grub/themes/UKUI/


icons/ukui/8x8 icons/ukui-icon-theme-default/8x8
icons/ukui/14x14 icons/ukui-icon-theme-default/14x14
icons/ukui/14x14@2x icons/ukui-icon-theme-default/14x14@2x
icons/ukui/16x16 icons/ukui-icon-theme-default/16x16
icons/ukui/16x16@2x icons/ukui-icon-theme-default/16x16@2x
icons/ukui/22x22 icons/ukui-icon-theme-default/22x22
icons/ukui/24x24 icons/ukui-icon-theme-default/24x24
icons/ukui/24x24@2x icons/ukui-icon-theme-default/24x24@2x
icons/ukui/32x32 icons/ukui-icon-theme-default/32x32
icons/ukui/32x32@2x icons/ukui-icon-theme-default/32x32@2x
icons/ukui/48x48 icons/ukui-icon-theme-default/48x48
icons/ukui/48x48@2x icons/ukui-icon-theme-default/48x48@2x
icons/ukui/64x64 icons/ukui-icon-theme-default/64x64
icons/ukui/64x64@2x icons/ukui-icon-theme-default/64x64@2x
icons/ukui/96x96 icons/ukui-icon-theme-default/96x96
icons/ukui/96x96@2x icons/ukui-icon-theme-default/96x96@2x
icons/ukui/128x128 icons/ukui-icon-theme-default/128x128
icons/ukui/128x128@2x icons/ukui-icon-theme-default/128x128@2x
icons/ukui/256x256 icons/ukui-icon-theme-default/256x256
icons/ukui/256x256@2x icons/ukui-icon-theme-default/256x256@2x
icons/ukui/scalable icons/ukui-icon-theme-default/scalable
icons/ukui/symbolic icons/ukui-icon-theme-default/symbolic









